apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: repo-url
    - name: app-name
      default: tax-calculator
    - name: branch
      default: main
  tasks:
  
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
        
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init      
    - name: npminstall
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: npm
      runAfter:
        - clone
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: dockerconfig-ws
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
      runAfter:
        - tests